In [2]:
import torch
import numpy as np

In [1]:
def describe(tensor):
    print("type: ", tensor.type())
    print("shape: ", tensor.shape)
    print("values: ", tensor)

Make random tensor

In [17]:
torch.Tensor(2, 3)

tensor([[ 2.2394,  1.1181, -0.3523],
        [-0.3345,  0.1105,  2.8880]])

In [18]:
torch.rand(2, 3) #uniform random

tensor([[0.3722, 0.7043, 0.7973],
        [0.3196, 0.2361, 0.9395]])

In [19]:
torch.randn(2, 3) #random normal

tensor([[-0.3827,  0.9732, -0.0212],
        [ 0.3694,  1.1381, -2.6075]])

Filled tensors

In [21]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
torch.Tensor(2, 3).fill_(5)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

Tensor from list and array

In [24]:
torch.Tensor([[1, 2, 3], [4, 5, 6]])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
torch.from_numpy(np.random.rand(2, 3))

tensor([[0.0956, 0.8432, 0.9256],
        [0.7128, 0.6033, 0.0396]], dtype=torch.float64)

Type conversion

In [28]:
torch.FloatTensor([2, 3, 4]).long().type()

'torch.LongTensor'

In [29]:
torch.tensor([1, 2, 3], dtype=torch.int64)

tensor([1, 2, 3])

Operations

In [30]:
x = torch.tensor([1, 2, 3])

In [34]:
torch.add(x, x)

tensor([2, 4, 6])

In [32]:
x + x

tensor([2, 4, 6])

In [37]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [40]:
x = x.view(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [41]:
torch.sum(x, dim=0)

tensor([3, 5, 7])

In [43]:
torch.sum(x, dim=1)

tensor([ 3, 12])

In [45]:
torch.transpose(x, 0, 1)

tensor([[0, 3],
        [1, 4],
        [2, 5]])

Slicing

In [46]:
x[:1, :2]

tensor([[0, 1]])

In [47]:
x[0, 2]

tensor(2)

# Differentiation

Finding the derivative of the function y = x<sup>2</sup> at x = 2:

1. Define the tensor and the function

In [6]:
x = torch.tensor(2.0, requires_grad=True)
y = x**2

2. Compute derivative of the function

In [9]:
y.backward()

C:\ProgramData\Anaconda3\lib\site-packages\torch\autograd\__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


3. Get the value of the derivative at x=2 by calling the gradient of x

In [10]:
x.grad

tensor(4.)

## Partial derivatives

Finding the partial derivatives of y = uv + v<sup>2</sup> wrt u and v

1. Define u and v, and the function

In [15]:
u = torch.tensor(1.0, requires_grad=True)
v = torch.tensor(2.0, requires_grad=True)

y = u*v + v**2

2. Calculate the partial derivatives

In [16]:
y.backward()

3. Get the partial derivative wrt u and v

In [13]:
u.grad

tensor(2.)

In [14]:
v.grad

tensor(6.)

# Datasets

In [18]:
from torch.utils.data import Dataset

In [ ]:
import pandas as pd
df = 1

In [19]:
class my_dataset(Dataset):
    def __init__(self, length=100, transform=None):
        self.x = 2*torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.len = length
        self.transform = transform
        
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len

In [20]:
d1 = my_dataset()

In [22]:
len(d1)

100

In [23]:
d1[0]

(tensor([2., 2.]), tensor([1.]))

## Transforms

In [26]:
class transform1(object):
    def __init__(self, addx=2, muly=2):
        self.addx = addx
        self.muly = muly
        
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x, y
        return sample

In [28]:
trans1 = transform1()

In [30]:
df_transformed = my_dataset(transform=trans1)

### Multiple transforms

In [32]:
from torchvision import transforms

In [36]:
df_transformed = transforms.Compose([trans1(), trans1()])

TypeError: __call__() missing 1 required positional argument: 'sample'

## Image datasets

In [37]:
directory = "/resources/images"

In [ ]:
df = pd.read_csv("index.csv")