In [1]:
import numpy as np

#Arrays

NumPy arrays contain the same type of data values.

##Creation

In [2]:
# Create an array filled with a linear sequence starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
#The datatype of array values can be set explicitly
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [5]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.03693447, 0.05093462, 0.30785547],
       [0.94752317, 0.35472557, 0.82370913],
       [0.05225704, 0.4549186 , 0.22659304]])

In [6]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 6, 3],
       [1, 1, 6],
       [4, 4, 2]])

In [7]:
#turning a list into an array:
np.array([3, 1, 4, 1, 5])

array([3, 1, 4, 1, 5])

In [8]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

In [0]:
# Create an uninitialized array of three integers
np.empty(3)
# The values will be whatever happens to already exist at that memory location

##Attributes

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [0]:
x1 = np.random.randint(10, size=6)  # One-dimensional array

print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)


x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array

print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)


x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

In [0]:
print("dtype:", x1.dtype)

In [0]:
print("itemsize:", x3.itemsize, "bytes") #gives the size of each array element
print("nbytes:", x3.nbytes, "bytes") #gives the total size of the array

##Indexing

Of one-dimensional array

In [0]:
x1
print(x1[0], x1[3], x1[-2])

Of multi-dimensional array

In [14]:
x2
print(x2[0,0], x2[2,0], x2[2, -1])

6 9 5


Unlike Python lists, NumPy arrays have a fixed type. If you attempt to insert a floating-point value to an integer array, the value will be silently truncated. 

In [15]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 4, 3, 1, 9, 0])

##Slicing

###One dimensional

To access a slice of an array x, use this:
x[start:stop:step]

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
print(x[:5])  # first five elements

print(x[5:])  # elements after index 5

print(x[4:7])  # middle sub-array

print(x[::2])  # every other element

print(x[1::2])  # every other element, starting at index 1

print(x[::-1])  # all elements, reversed

print(x[5::-2])  # reversed every other from index 5

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


###Multi dimensional

array[rows, columns]

In [21]:
x2

array([[6, 6, 9, 5],
       [1, 4, 4, 5],
       [9, 2, 5, 5]])

In [0]:
print(x2[:2, :3])  # two rows, three columns

print(x2[:3, ::2])  # all rows, every other column

print(x2[::-1, ::-1]) # reversed

For accessing single rows/columns combine indexing and slicing

In [0]:
print(x2[:, 0])  # first column of x2

print(x2[0, :])  # first row of x2

print(x2[0])  # simply accessing a row, hence removing the need to enter tye column; equivalent to x2[0, :]

##Reshaping

In [0]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

An array can be turned into a row or column vector or a matrix by:

In [0]:
x = np.array([1, 2, 3])


print(x.reshape((1, 3))  # row vector via reshape

(a = x[np.newaxis, :]  # row vector via newaxis

print(x.reshape((3, 1)))  # column vector via reshape

print(x[:, np.newaxis])  # column vector via newaxis

##Copying

In [0]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

If we modify a subarray, the original array is changed. So, splitting for representational purposes must be done on copies of arrays.

##Joining

###One dimensional

In [36]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


###Two dimensional

In [0]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
a = np.concatenate([grid, grid])
# concatenate along the second axis (zero-indexed)
b = np.concatenate([grid, grid], axis=1)

print(a)
print(b)

Or, use the easier to read methods vertical stack and horizontal stack

In [0]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
c = np.vstack([x, grid])


# horizontally stack the arrays
y = np.array([[99],
              [99]])
d = np.hstack([grid, y])

print(c)
print(d)

##Splitting

In [39]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [0]:
grid = np.arange(16).reshape((4, 4))
grid

upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

left, right = np.hsplit(grid, [2])
print(left)
print(right)

In [0]:
gfg = np.array([[1, 2, 5], 
                [3, 4, 10], 
                [5, 6, 15], 
                [7, 8, 20]]) 
  
gfg = gfg.reshape(1, 2, 6) 
print(gfg) 
  
gfg = np.dsplit(gfg, 2) 
print(gfg)

#n